### ISSUE TITLE
Link underline invisible

### ISSUE THREAD

**Issue by mrflix** [philipwalton/blog#47] opened 2015-12-07 00:22 UTC
This is what a paragraph looks like on my latest Chrome on a non-retina MacBook 13':
![screen shot 2015-12-07 at 01 04 08](https://cloud.githubusercontent.com/assets/60777/11616551/98fe33c4-9c7e-11e5-94d8-8988a0dc3b64.png)

This is what it should look like:
![screen shot 2015-12-07 at 01 03 58](https://cloud.githubusercontent.com/assets/60777/11616553/9f38de2e-9c7e-11e5-95f9-c69030e16b61.png)

On my machine the `font-size: 1.0625em` converts to `17px`. The `line-height: 1.47` converts to `24.99px`. The text bounding-box for each row is `20px`. I don't know how thats calculated. I thought like `17 + (24.99 - 17) / 2` but that results in `20.995` – does it round down? Never the less – the gradient underline background is positioned at `0 1.25em` which results in `0 21.25px`. Since thats outside the text bounding box of `20px` the underline doesn't render. `0 1.17em` is the first value that goes below `20px` (`19.89px`) and makes the underline visible.

**Comment by philipwalton** [comment] 2015-12-07 01:10
Thanks for looking into this. It's weird to me that I can't reproduce this myself. I don't have a MacBook 13', but even on non-retina screen types using crossbrowsertesting.com, I can always see the underline.

How are you determining the bounding box? When I check in Chrome devtools, I see 23px.

**Comment by philipwalton** [comment] 2015-12-07 01:12
Actually, I think I know what the problem is. Are you blocking web fonts? Can you confirm that the text you're looking at is rendered using Georgia?

When I let it fall back to Georgia I also see a bounding box of 20px.

**Comment by philipwalton** [comment] 2015-12-07 09:52
Should be fixed by 51256024500de72da75a270bcd06811b53801af2. Let me know if you're still seeing the issue.

**Closed by philipwalton** 2015-12-07 09:52 UTC

**Comment by mrflix** [comment] 2015-12-08 20:20
Ah yeah, Ghostery blocked Noto Serif. It rendered in Georgia. Fixed now. Thanks!
