### ISSUE TITLE
JS-triggered navigation doesn't allow for opening in new tabs

### ISSUE THREAD

**Issue by tigt** [philipwalton/blog#48] opened 2015-12-20 01:33 UTC
The JS-swap-in page navigation is fast and cool, but right-clicking/<kbd>Ctrl</kbd>+clicking to open links in new tabs fires the navigation also.

Not sure about touch, but that might be an issue too.

**Comment by philipwalton** [comment] 2015-12-20 17:34
I'm not able to reproduce this. I can right click on any of the links to open them in a new tab via an actual right click or CTRL+click (on my Mac).

Right clicks shouldn't produce click events ([reduced test case](http://codepen.io/anon/pen/VejwXZ?editors=101)), and I have [logic that should allow for cmd/ctrl-clicking](https://github.com/philipwalton/blog/blob/master/assets/javascript/content-loader.js#L104). 

Can you tell me what browser/OS you're on?

**Comment by tigt** [comment] 2015-12-20 21:35
Ah, you're right, I should have looked closer; this is a double finger-click on a MacBook trackpad. Firefox 42.

**Comment by philipwalton** [comment] 2015-12-21 00:38
Ok, it looks like Firefox registers a click event for two-finger tap and Chrome does not. It should be fixed now via 2a345acfb94240a869fb490475d254003bf18916. Let me know if you're still having issues, and thanks for reporting!

**Closed** 2016-02-16 05:50 UTC
